### ISSUE TITLE
getting error after updating this morning

### ISSUE THREAD

**Issue by jpetersenODOE** [MscrmTools/MscrmTools.PortalRecordsMover#55] opened 2022-05-20 18:43 UTC
![Screenshot_1](https://user-images.githubusercontent.com/105944649/169592296-7b9839c4-a8c0-4ca4-a2cc-87a92446a26e.png)
i just did an update this morning and every time I try to load records I get the attached error.  I am working on a big migration and could really use your tool.  Any help would be appreciated.

**Comment by albertoaven** [comment] 2022-05-20 21:30
The issue is the line 132 of the file "RecordsListerControl.cs" in the operation in the "AttributeTypeCode.PartyList" case.

```
 switch (amd.AttributeType.Value)
            {
                case AttributeTypeCode.PartyList:
                    return string.Join(", ", record.GetAttributeValue<EntityCollection>(value).Entities.Select(e => e.GetAttributeValue<EntityReference>("partyid")?.Name).ToArray());
```

I have reverted locally the last update and all back to work as before.

**Comment by MscrmTools** [comment] 2022-05-21 05:52
Ok, I will double check what is wrong with this line and fix it

**Comment by MscrmTools** [comment] 2022-05-21 09:11
This should be fixed now.

**Closed** 2022-05-21 09:11 UTC

**Comment by jpetersenODOE** [comment] 2022-05-23 14:25
Yes thank you it started working Friday afternoon which was a big relief.
