### ISSUE TITLE
Web Pages records are not getting imported

### ISSUE THREAD

**Issue by pd28** [MscrmTools/MscrmTools.PortalRecordsMover#3] opened 2017-07-20 10:24 UTC
Hi Tanguy, 

thank you for tool, this is really helpful. we tried this tool with Dynamics 365 online Portal . 
but while importing data to target organisation we are getting issues due to which Web pages are not getting copied. Can you please help us to resolve issue. we are struggling to copy portal data, quick help would be appreciated. 

[MscrmTools.PortalRecordsMoverlog.docx](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/1161936/MscrmTools.PortalRecordsMoverlog.docx)

**Comment by MscrmTools** [comment] 2017-07-20 10:56
can you confirm that your web pages have a partialurl value?

**Comment by poojabhagwat28** [comment] 2017-07-20 11:09
yes, every web page is having partial URL.

**Comment by MscrmTools** [comment] 2017-07-20 11:14
Do they also have a parent page defined?

can you also check that this value is properly exported in the output file?

**Comment by poojabhagwat28** [comment] 2017-07-21 06:42
only 3 pages(and its child pages ) are not having parent page value including Home page. 
we have Feedback web page which is not getting imported , attached is the format for Parent page details of Feedback web page from exported XML file 

[parent page format.txt](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/1164664/parent.page.format.txt)

**Comment by poojabhagwat28** [comment] 2017-07-24 07:14
hello ,  is there any update on the issue. let us know if any other details we have to share.

**Comment by MscrmTools** [comment] 2017-07-24 07:41
I guess I know what the problem is. To avoid any unexisting reference, I remove all entityreference, then update all records with these entityreference.
It seems that web page does not like it
I will need to review my algorythm. 

Can't say when yet...

**Comment by edddduuuu** [comment] 2017-07-25 03:58
how can i remove the entityreference and which entityreference? i'm also having problem in importing the data, mostly in WebPages, UrlHistory, and ContentAccessLevel.

**Comment by MscrmTools** [comment] 2017-07-25 06:51
You can't. This is something I need to handle in the code

**Comment by MscrmTools** [comment] 2017-07-25 09:30
May I get the error message related to UrlHistory and ContentAccessLevel

**Comment by edddduuuu** [comment] 2017-07-25 09:49
for URLHistory:
Error	~/add-general-reports (URL History/05b5a573-7b6b-e711-8105-fc15b428fbe0): Adx_webpage With Id = abeb7ab5-7a6b-e711-80f9-c4346bada540 Does Not Exist
Error	~/extending (URL History/06b5a573-7b6b-e711-8105-fc15b428fbe0): Adx_webpage With Id = 66186f21-7a6b-e711-80f9-c4346bac9f9c Does Not Exist

Content Access Level:
Error	Default (Content Access Level/b8ab957d-e507-48da-9774-4d6723809d3d): Your configuration allows you to create a maximum of 1 default content access levels.

**Comment by MscrmTools** [comment] 2017-07-25 11:57
Can you test with this updated version?
You have to export records again and import them as both export and import process have been updated.

[MscrmTools.PortalRecordsMover.zip](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/1173042/MscrmTools.PortalRecordsMover.zip)

**Comment by edddduuuu** [comment] 2017-07-25 15:16
I tested the updated version. New error message occurred for WebPage and
same error with ContentAccessLevel. Importing URLHistory was resolved but
importing Web Form Session failed.

For Content Acces Level:
Error Default (Content Access Level/b8ab957d-e507-48da-9774-4d6723809d3d):
Your configuration allows you to create a maximum of 1 default content
access levels.

For new error message for WebPage:
Error Add General Reports (Web Page/7ed7d7b2-7a6b-e711-9401-0003ff6d5b63):
No website is specified.
Error Extending (Web Page/a228f320-7a6b-e711-9401-0003ff6d5b63): No website
is specified.
Error View General Reports (Web Page/f69cef13-7f6b-e711-80fb-c4346bac4e40):
Adx_webpage With Id = 9a14f012-7f6b-e711-9401-0003ff6d5b63 Does Not Exist
Error Supervisor Reports (Web Page/bfaebac4-796b-e711-80f9-c4346bac9f9c): 2
is not a valid status code for state code Adx_webpageState.Active on
adx_webpage with Id bfaebac4-796b-e711-80f9-c4346bac9f9c.

For Web Form Session:
Error (Web Form Session/7d1a96ea-036e-e711-9401-0003ff6d5b63): 2 is not a
valid status code for state code adx_webformsessionState.Active on
adx_webformsession with Id 7d1a96ea-036e-e711-9401-0003ff6d5b63.

**Comment by MscrmTools** [comment] 2017-07-25 15:20
Ok, One probleme might be due to StateCode removal, so it tries to import inactive record, so it fails

For web pages, let me check for the "No website is specified"

**Comment by edddduuuu** [comment] 2017-07-26 01:08
Thanks Tanguy. Just lemme know if u have updates and lemme test it for you.

**Comment by poojabhagwat28** [comment] 2017-08-02 06:40
Hello , 
is there any update on this ? we are really looking forward for your tool.

thanks !

**Comment by MscrmTools** [comment] 2017-08-02 07:48
Can you test this version? It does not handle inactive records yet but other error messages "should" work
[MscrmTools.PortalRecordsMover.zip](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/1193035/MscrmTools.PortalRecordsMover.zip)

**Comment by poojabhagwat28** [comment] 2017-08-02 12:17
hello, 

we tried latest version , and this time no web pages and notes gets transferred. got below errors - 


1. Note/6470534c-f6ec-e611-93ff-0003ff6c396e): Adx_webfile With Id = 6370534c-f6ec-e611-93ff-0003ff6c396e Does Not Exist 
2. Error	modify-dialogue.css (Web File/64202007-e941-e711-9401-0003ff6c5496): 2 is not a valid status code for state code Adx_webfileState.Active on adx_webfile with Id 64202007-e941-e711-9401-0003ff6c5496. 
[MscrmTools.PortalRecordsMover2.txt](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/1193764/MscrmTools.PortalRecordsMover2.txt)


3. Error	Event Details (Web Page/cd99b669-cf07-e711-80ee-c4346bac9f9c): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal. 
4. Error	 (Note/7b12095c-6a52-e711-9400-0003ff6c7987): Object reference not set to an instance

**Comment by MscrmTools** [comment] 2017-08-02 12:23
Are you sure you used latest version? I guess 2 and 3 should not happen with this version

**Comment by poojabhagwat28** [comment] 2017-08-02 12:54
Yes, we used latest DLL and replaced that in XRM tool box plugin folder. let me know if we are missing any other step in this case. i will give one more try.

**Comment by MscrmTools** [comment] 2017-08-02 13:43
I changed the attached file so maybe you downloaded the first version. Can you download again from github and try again?

**Comment by poojabhagwat28** [comment] 2017-08-03 11:23
hi Tanguy, 

we tried the version which is added in Git hub only. from your comment as well as from source code given her in Git hub. still we are getting same errors.

**Comment by MscrmTools** [comment] 2017-08-03 13:01
Ok, I tested:

- inactive records : ok
- pages with multiple levels : ok
- webfile : ok

Please check this version

[MscrmTools.PortalRecordsMover_20170803.zip](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/1197248/MscrmTools.PortalRecordsMover_20170803.zip)

**Comment by MscrmTools** [comment] 2017-08-03 13:53
Oh! and don't forget to export data again. Do not use the same previously exported file

**Comment by edddduuuu** [comment] 2017-08-03 15:42
Hi,

Just tested the latest dll. Still got some errors on webpage import and new
warning occurred.

2017-08-03 11:37:43.323 PM Error View Supervisor Reports (Web
Page/2222d214-846b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:37:43.823 PM Error View Manager Reports (Web
Page/a1d468f5-836b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:37:44.182 PM Error View General Reports (Web
Page/9a14f012-7f6b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:37:50.546 PM Error New General Report (Web
Page/3b079cc1-5b6c-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:04.353 PM Error View Supervisor Reports (Web
Page/78da1a11-846b-e711-80f9-c4346bacae18): Adx_webpage With Id =
2222d214-846b-e711-9401-0003ff6d5b63 Does Not Exist
2017-08-03 11:38:04.416 PM Error View Manager Reports (Web
Page/6e55a9f6-836b-e711-80f9-c4346bacae18): Adx_webpage With Id =
a1d468f5-836b-e711-9401-0003ff6d5b63 Does Not Exist
2017-08-03 11:38:04.478 PM Error View General Reports (Web
Page/f69cef13-7f6b-e711-80fb-c4346bac4e40): Adx_webpage With Id =
9a14f012-7f6b-e711-9401-0003ff6d5b63 Does Not Exist
2017-08-03 11:38:09.232 PM Error New General Report (Web
Page/8e119fc2-5b6c-e711-80f9-c4346bac9f9c): Adx_webpage With Id =
3b079cc1-5b6c-e711-9401-0003ff6d5b63 Does Not Exist
2017-08-03 11:38:28.570 PM Error View Supervisor Reports (Web
Page/2222d214-846b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:28.780 PM Error View Manager Reports (Web
Page/a1d468f5-836b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:28.983 PM Error View General Reports (Web
Page/9a14f012-7f6b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:29.342 PM Error New General Report (Web
Page/3b079cc1-5b6c-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:29.530 PM Error View Supervisor Reports (Web
Page/2222d214-846b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:29.717 PM Error View Manager Reports (Web
Page/a1d468f5-836b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:29.889 PM Error View General Reports (Web
Page/9a14f012-7f6b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:30.077 PM Error New General Report (Web
Page/3b079cc1-5b6c-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:30.248 PM Error View Supervisor Reports (Web
Page/2222d214-846b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:30.467 PM Error View Manager Reports (Web
Page/a1d468f5-836b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:30.686 PM Error View General Reports (Web
Page/9a14f012-7f6b-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:30.920 PM Error New General Report (Web
Page/3b079cc1-5b6c-e711-9401-0003ff6d5b63): No website is specified.
2017-08-03 11:38:30.920 PM Warning Max loop count reached! Exit record
first cycle processing !

**Comment by MscrmTools** [comment] 2017-08-03 16:26
Is this a full export or did you selected items from a specific date?

**Comment by edddduuuu** [comment] 2017-08-03 22:46
It's the full report exported since the day i created the crm online
instance.

**Comment by edddduuuu** [comment] 2017-08-14 02:35
Hi,
Is there any update on portal records mover? We are also looking forward for your tool. :)

**Comment by MscrmTools** [comment] 2017-08-14 06:17
I'm in holidays for next two weeks... no work planned until then

**Comment by edddduuuu** [comment] 2017-08-22 10:26
Hi Tanguy,

I've tried retrieving records from new working adx portal with customizations and functionalities using the latest dll. 

First, i started selecting all loaded items. Get records from website: checked. Get only active records: checked.
*Error occurred on retrieving 'Note': "An error occurred: 'Annotation' entity doesn't contain attribute with Name= 'statecode'."
So i skipped retrieving 'Note' by deselecting it and started retrieve records.
*Error occurred on retrieving 'Forum Notification': "An error occurred: 'adx_forumnotification' entity doesn't contain attribute with Name= 'adx_websiteid'."
So i skipped retrieving 'Forum Notification' by deselecting it and started retrieve records.
*Error occurred on retrieving 'Page Notification': "An error occurred: 'adx_pagenotification' entity doesn't contain attribute with Name= 'adx_websiteid'."
So i skipped retrieving 'Page Notification' by deselecting it and started retrieve records.
*Error occurred on retrieving 'Invitation': "An error occurred: 'adx_invitation' entity doesn't contain attribute with Name= 'adx_websiteid'."
So i skipped retrieving 'Invitation' by deselecting it and started retrieve records.
*No error occurred. 
So i selected all retrieved records and started Export records. Records Exported successfully.

Next, I imported the necessary custom solution from working crm online instance to newly created crm online instance with Portal-Add On configured.

Then, i connected the newly created crm to XrmToolbox, selected the exported portal record backup in xml format, and initiated the import records.
*Error occurred in importing the following:
 Web Page: Success: 36, Error: 81
 URL History: Success: 397, Error: 48
 Content Access Level: Success: 2, Error: 4
*Records imported with Information: "Import complete with errors"

Tried importing again. 
*Error occurred counts were the same, but i noticed in log file i was having web page errors which is not existing on the portal i'm working on.  It looks like a mixed up with some testing i've done using different portals.

But when i checked the newly created portal, the customizations and functionalities are working. Thanks Tanguy for this tool. 

I'll test it again then i'll give you feedback if i'm still having same issues.

**Comment by edddduuuu** [comment] 2017-08-24 09:08
Hi Tanguy,

I tested the backup portal i created. I just noticed that some web files and web templates are successfully imported that's why the customizations from previous portal show in new portal except for web pages. The import became limited only to default webpages such as sign in, profile and home. There's also an issue about log files. Still looking forward for updates. 

Thanks.

**Comment by MscrmTools** [comment] 2017-08-29 08:07
Thank you for all these information. I will try to update the tool but I just came back from holidays and I have lot of work to do before working on my personal stuff

**Comment by edddduuuu** [comment] 2017-08-31 08:30
Hi Tanguy,

I was hoping to import without errors, even though most of the portal data configurations were successfully imported. I had errors on importing certain web pages, so I checked these web pages in crm. I noticed duplicate localized content.
![image](https://user-images.githubusercontent.com/30424815/29913692-6ac43c50-8e68-11e7-98d0-e5c3a293ec8c.png)
![image](https://user-images.githubusercontent.com/30424815/29913830-e1c08c46-8e68-11e7-87a8-1ed7bb0e5132.png)
![image](https://user-images.githubusercontent.com/30424815/29913867-fe769600-8e68-11e7-8972-a129a27790bf.png)

I only tried importing web pages only:
![image](https://user-images.githubusercontent.com/30424815/29913964-5dfc27c0-8e69-11e7-8a2a-519243fef806.png)

These are the errors shown in log file:
Error	Story-article-1 (Web Page/5af3cc66-ae88-e711-80fe-c4346bac9f9c): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.
Error	Story-article-1 (Web Page/c5d72558-6d8d-e711-80fe-c4346bada540): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.
Error	Run For Hope (Web Page/d8abb732-6d8d-e711-80fe-c4346bada540): Web page with same partial url and parent page already exists.
Error	Chat Bot (Web Page/1a80aa51-6d8d-e711-80fe-c4346bada540): Web page with same partial url and parent page already exists.
Error	Story-article-1 (Web Page/5af3cc66-ae88-e711-80fe-c4346bac9f9c): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.
Error	Story-article-1 (Web Page/c5d72558-6d8d-e711-80fe-c4346bada540): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.
Error	Run For Hope (Web Page/d8abb732-6d8d-e711-80fe-c4346bada540): Web page with same partial url and parent page already exists.
Error	Chat Bot (Web Page/1a80aa51-6d8d-e711-80fe-c4346bada540): Web page with same partial url and parent page already exists.
Error	Story-article-1 (Web Page/5af3cc66-ae88-e711-80fe-c4346bac9f9c): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.
Error	Story-article-1 (Web Page/c5d72558-6d8d-e711-80fe-c4346bada540): Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal.
Error	Run For Hope (Web Page/d8abb732-6d8d-e711-80fe-c4346bada540): Web page with same partial url and parent page already exists.
Error	Chat Bot (Web Page/1a80aa51-6d8d-e711-80fe-c4346bada540): Web page with same partial url and parent page already exists.
Warning	Max loop count reached! Exit record first cycle processing !

I'm still looking forward for updates. :)

Thanks.

**Comment by poojabhagwat28** [comment] 2017-09-21 06:33
hi Tanguy , 
any updates on this? this point of time Microsoft even don't have solution for portal deployment. 
can you please help us with this.

**Comment by MscrmTools** [comment] 2017-09-21 06:46
I do understand the expectation on this tool but you have to understand that:
- the tool works as expected on my portals so it is not easy to fix bugs I can't reproduce
- I have a job (yes, being MVP is not a full time position, it's even not a position at all) and I don't have so much time these days to work on my tools
- the project is open source: if you have some code skills or know colleagues with some, you (they) can help by finding and fixing bugs that you see

**Comment by hoseph** [comment] 2017-10-02 00:00
@edddduuuu 
This is an adxstudio plugin issue. You can resolve it by disabling the validation steps when importing.
 
Plugin assembly: Adxstudio.Xrm.Plugins
Step: Adxstudio.Xrm.Plugins.MultiLanguage.WebPageValidationPlugin: Update of adx_webpage
Step: Adxstudio.Xrm.Plugins.MultiLanguage.WebPageValidationPlugin: Create of adx_webpage

https://bernado-nguyen-hoan.com/2017/09/26/fixing-issues-with-migrating-adxstudiocrm-portal-v8-using-configuration-migration-tool/

**Comment by medicstuder** [comment] 2017-10-23 20:13
I can confirm what @edddduuuu stated.  If you are doing an initial import, turn your adx plugins off.  Do your import, then turn plugins back on.  You only need to do this on your initial import, after that you shouldn't need to turn off the plugins.  If I was the dev of this tool I would close this bug as fixed as it is not an issue with the xrmtookbox plugin.

**Comment by nega73** [comment] 2017-11-03 19:41
Hi all,

I was just struggling with the Portal Records Mover plugin from XRMToolBox and kept getting the references errors "/.":

"Value of Partial URL field of the Home Page of your website can only be /. Any other value will lead to issues in your Portal."

The way I circumvented it was that I exported and imported first the root (Info) web-pages and then the content (localized) web-pages... no errors with this approach!!! 

One more thing to note is that upon the Info (root) Web Pages importing, a default Content (localized English or so) Web Page is created apparently automatically by the Import tool or by CRM Portals itself, which I opted to remove. It can be recognized easily because it has the exact same name as the root imported webpage and shows localized English or so. Easiest is to remove it right after importing the root (Info) page, so if you import Content Pages with same exact name then you don't get confused... 
My way was actually giving the Contact pages a suffix in the name as well EN or FR, so it can be easily recognizable.

Hope that helps!

All thanks and virtual cookies are welcome and well received!

Thanks guys and Happy CRM-ing!!!

cheers!

Gabe (gabrines@hotmail.com)

**Comment by burchjustin** [comment] 2018-04-05 19:27
To piggyback on the last few comments:
1. The Localized Content is created by another set of Plugins (also "Adxstudio.Xrm.Plugins.MultiLanguage.*") - I tend to disable the 4 MultiLanguage Plugins and re-enabling after create
2. These only need to be disabled on Create of a new Web Page
3. Make sure you do some form of update on your web pages after re-enabling the Validation Plugins, otherwise you will run into issues like https://url/parentpage/page-partial-url showing "Page Not Found" rather than routing to https://url/parentpage/page-partial-url/

**Comment by MscrmTools** [comment] 2018-05-22 13:37
I will try to add these steps in the tool directly. 

Thank you for the feedback

**Comment by robertbastien** [comment] 2018-06-08 16:13
Hi Tanguy,

Great tool but I also encountered all the issues around the adx_webpage entity plugins and it's a major pain point when we promote so I can't wait for your next release. 

Regards,

Robert

**Comment by burchjustin** [comment] 2018-06-12 21:57
@MscrmTools - Hi Tanguy - these changes work perfectly for me. I was able to create a hierarchy (test-parent, child of Home & test-child, child of test-parent) and could move both web pages + localized content in one single step.  👍 Is it possible to get a fix for the "modified on or after" filter? Regardless, fantastic tool!

**Comment by MscrmTools** [comment] 2018-06-13 06:46
I'm not sure what you are refering to when talking about "fix for the "modified on or after" filter" but there was a PR for something that seems related. It will be included in next release too

**Closed** 2018-06-13 06:53 UTC

**Comment by readyxrm** [comment] 2018-06-18 19:22
Hi Tanguy,  On the tabs that show the records, is there a way to modify the views or at least have each section show both "modified on" and "created on" ?  See screen shot for what I am looking for...
![portaldatamover](https://user-images.githubusercontent.com/18264651/41557334-5552aba8-730b-11e8-96f3-d08b0788da9c.jpg)

**Comment by MscrmTools** [comment] 2018-06-18 19:58
The views used are the quick find ones so you can change your self the layout if needed
